### ISSUE TITLE
Direct way to download and buffer?

### ISSUE THREAD

**Issue by IngwiePhoenix** [fgenesis/minihttp#1]
Hey.

I am trying to implement the download and buffer method. I.e.:

    std::string mydata = ht->Download("http://google.com");

Kind regards, Ingwie

**Comment by fgenesis** [comment]
Ask and you shall receive: Done in d72ac19eb444. See example1.cpp, and the related warning in minihttp.h.
Nevertheless, adding a simple and direct download function was a fairly good idea, and easy enough to do without pulling in additional dependency garbage.
