### ISSUE TITLE
class DLSocket  have a bug, always request memory and crash

### ISSUE THREAD

**Issue by sisong** [fgenesis/minihttp#10]
`(bufcap + size + 1 >= bufsz)` changed  to `(bufsz + size + 1 >= bufcap)`?

**Comment by fgenesis** [comment]
Oops! Good catch! Care to open a PR? credit where credit is due.
(How did that EVER work? That bug was in there for basically forever and we've been using this for an IRC bot that fetches every URL posted and apparently that was never an issue... lol wtf)
